#!/usr/bin/env bash
# Script that installs Nginx server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw "Nginx HTTP"
echo "Hello world!" | sudo tee /var/www/html/index.html
sudo nginx -t

sudo service nginx reload
